version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - python3 -m compileall src/app.py
      - mv src/__pycache__/*.pyc ./app.pyc
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - app.pyc

